urlshortener/authenticate/urls.py
from django.urls import path
from . import views
app_name='authenticate'
urlpatterns=[
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup, name="signup"),
    path("urlshortner/", views.urlshortner, name='urlshortner')
]

urlshortener/urlhandel/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.make,name="make"),
    path('<str:token>', views.home ,name="home")
]

urlshortener/urlhandeler/urls.py
from django.urls import path
from . import views
app_name='urlhandeler'
urlpatterns=[
    path('',views.index,name="index")
]

urlshortener/urlshortener/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticate.urls')),
    path('', include('urlhandel.urls'))
]

urlshortener/authenticate/models.py
from django.db import models
from urlhandel.models import short_urls
# Create your models here.
class User(models.Model):
    username=models.CharField(max_length=200)
    password=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    urls= models.ManyToManyField(short_urls,related_name="urls", blank=True)
    def __str__(self):
        return f"{self.username}"

urlshortener/urlhandel/models.py
from django.db import models

# Create your models here.
class short_urls(models.Model):
    short_url=models.CharField(max_length=20)
    long_url=models.URLField('Url', unique=True)
    
    def __str__(self):
        return f"{self.short_url} is for {self.long_url}"

urlshortener/urlhandel/forms.py
from django import forms
from .models import short_urls

class UrlForm(forms.ModelForm):
    class Meta():
        model=short_urls
        fields=['long_url']
        exclude=['short_url']

urlshortener/authenticate/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login , logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
#from django.contrib.auth.models import User
from .models import User
from urlhandel.views import make
# Create your views here.
def login_view(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        if User.objects.filter(username=username).exists() and User.objects.filter(password=password).exists():
             return HttpResponseRedirect(reverse('authenticate:urlshortner'))
        else:
            return HttpResponseRedirect(reverse('authenticate:signup'))
    return render(request, "login.html")

def signup(request):
    if request.method=='POST':
        username=request.POST['username']
        # password=request.POST['password'] not needed at the moment
        confirm_password=request.POST['password1']
        # email= request.POST['email']  not needed at the moment
        confirm_email= request.POST['email1']
        
        user=User(username=username,password=confirm_password,email=confirm_email)
        user.save()
        return HttpResponseRedirect(reverse('authenticate:urlshortner'))

    return render(request, "signup.html")
#hi
def urlshortner(request):
    return make(request)

urlshortener/urlhandel/views.py
from django.shortcuts import render,redirect
from .shortener import shortner
from .models import short_urls
from .forms import UrlForm
from authenticate.models import User
# Create your views here.
def home(request, token):
    long_url= short_urls.objects.filter(short_url=token)[0]
    return redirect(long_url.long_url)
def make(request):
    form=UrlForm(request.POST)
    a=''
    url=User.urls.all()
    if request.method=="POST":
        if form.is_valid():
            Newurl=form.save(commit=False)
            a= shortner().issue_token()
            Newurl.short_url=a
            Newurl.save()
        else:
            form=UrlForm()
            a="Invalid form"
    return render(request,"home.html",{
        'form':form,
        'urls':url
    })

urlshortener/authenticate/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
        <style>
            body{background-color:#CB4541;
}
		form{
                text-align: center;
                margin-top: 300px;
            }
	.heading{
		text-align: center; 
		font-family: monospace; 
		font-size: 50px; 
		color: #000000; 
		border-color:blue; 
		border-style:dashed;
		left:200px;
		right:200px;
		top:100px;
		position:fixed;
		color: white;
  		text-shadow: 2px 2px 5px blue;
		box-shadow: 10px 10px 5px grey;
	}
		
	.heading:hover{color:red}
        </style>
    </head>
    <body>
	<div class="heading">
	<p>Welcome to <b>URL Shortner</b></p>
	</div>
	<form action="{%url 'authenticate:login'%}" method="POST">
			{%csrf_token%}
            <input placeholder="Username" name="username" type="text"><br><br>
            <input placeholder="Password" name="password" type="password"><br><br>
            <input type="submit"><br><br>
            <a href="{%url 'authenticate:signup'%}">Register here</a>
        </form>
    </body>

urlshortener/authenticate/templates/signup.html
<!DOCTYPE html>
<html>
    <head>
        <title>signup</title>
        <style>
            body{background-color:#CB4541;
}
		form{
                text-align: center;
                margin-top: 300px;
            }
	.heading{
		text-align: center; 
		font-family: monospace; 
		font-size: 50px; 
		color: #000000; 
		border-color:blue; 
		border-style:dashed;
		left:200px;
		right:200px;
		top:100px;
		position:fixed;
		color: white;
  		text-shadow: 2px 2px 5px blue;
		box-shadow: 10px 10px 5px grey;
	}
		
	.heading:hover{color:red}
        </style>
    </head>
    <body>
	<div class="heading">
	<p>Welcome to <b>URL Shortner</b></p>
	</div>
        <form action="{%url 'authenticate:signup'%}" method="POST">
            {% csrf_token %}
            <input placeholder="Username" name="username" type="text" minlength="6" ><br>
            <input placeholder="Password" name="password" type="password" minlength="8"><br>
            <input placeholder="Confirm password" name="password1" type="password"><br>

            <input placeholder="Email" name="email1" type="email"><br>
            <input type="submit"><br>
            <a href="{%url 'authenticate:login'%}">Already registered?</a>
        </form>
    </body>

urlshortener/urlhandel/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Url shortener</title>
    </head>
    <body>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" name="button">Save</button>
        </form>

        <h1>http://127.0.0.1:8000/urlshortner/{{a}}</h1>
        <ul>
            {%for url in urls%}
            <li>{{url}}</li>
            {% empty %}
            <li>Nothing</li>
            {% endfor %}
        </ul>
        <a href="{%url 'authenticate:login'%}">Login</a><br>
        <a href="{%url 'authenticate:signup'%}">Signup</a>
    </body>
</html>